In [69]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [70]:
df.head(5)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [71]:
df.rename(columns = {"entity": "Pais", "year" : "Anio", "life_expectancy_0" : "Esperanza_Vida"}, inplace = True)

In [72]:
df.head(3)

          Pais code  Anio  Esperanza_Vida
0  Afghanistan  AFG  1950         28.1563
1  Afghanistan  AFG  1951         28.5836
2  Afghanistan  AFG  1952         29.0138

In [73]:
df.set_index(["Pais", "Anio"])

                 code  Esperanza_Vida
Pais        Anio
Afghanistan 1950  AFG         28.1563
            1951  AFG         28.5836
            1952  AFG         29.0138
            1953  AFG         29.4521
            1954  AFG         29.6975
...               ...             ...
Zimbabwe    2019  ZWE         61.0603
            2020  ZWE         61.5300
            2021  ZWE         60.1347
            2022  ZWE         62.3601
            2023  ZWE         62.7748

[21565 rows x 2 columns]

In [74]:
df.head(3)

          Pais code  Anio  Esperanza_Vida
0  Afghanistan  AFG  1950         28.1563
1  Afghanistan  AFG  1951         28.5836
2  Afghanistan  AFG  1952         29.0138

In [75]:
df.loc[df["Pais"].str.contains("U", case = False, regex = True)]

                    Pais code  Anio  Esperanza_Vida
604             Anguilla  AIA  1950         55.0563
605             Anguilla  AIA  1951         55.5932
606             Anguilla  AIA  1952         56.0813
607             Anguilla  AIA  1953         56.5817
608             Anguilla  AIA  1954         57.0804
...                  ...  ...   ...             ...
21183  Wallis and Futuna  WLF  2019         77.9936
21184  Wallis and Futuna  WLF  2020         78.1637
21185  Wallis and Futuna  WLF  2021         77.4609
21186  Wallis and Futuna  WLF  2022         78.5005
21187  Wallis and Futuna  WLF  2023         78.6286

[7375 rows x 4 columns]

In [76]:
df.loc[df["code"].isnull()]

                                        Pais code  Anio  Esperanza_Vida
375                                 Americas  NaN  1770         34.8000
376                                 Americas  NaN  1830         34.8000
377                                 Americas  NaN  1850         35.1000
378                                 Americas  NaN  1870         35.1000
379                                 Americas  NaN  1900         41.0000
...                                      ...  ...   ...             ...
17703  Small Island Developing States (SIDS)  NaN  2019         72.0847
17704  Small Island Developing States (SIDS)  NaN  2020         71.7761
17705  Small Island Developing States (SIDS)  NaN  2021         69.8938
17706  Small Island Developing States (SIDS)  NaN  2022         72.1257
17707  Small Island Developing States (SIDS)  NaN  2023         72.7255

[1348 rows x 4 columns]

In [77]:
df.dropna(subset = ["code"], inplace = True)
df.isnull().sum()

Pais              0
code              0
Anio              0
Esperanza_Vida    0
dtype: int64

In [84]:
resultado = (
    df[df["Anio"] == 2020].groupby("Pais")["Esperanza_Vida"]
    .mean()
    .sort_values(ascending = True)
)
print(resultado)

Pais
Central African Republic    50.5959
Nigeria                     53.0724
Chad                        53.0818
Lesotho                     55.1325
Somalia                     57.0948
                             ...
Saint Barthelemy            84.0707
Macao                       84.6100
Japan                       84.6703
Hong Kong                   84.7073
Monaco                      86.0893
Name: Esperanza_Vida, Length: 246, dtype: float64